/*----------COMPROBACIONES DE LOS TRIGGERS-------*/

/*1.TRIGGER LLAMADO: TR_ENTRENADOR
EN ESTE TRIGGER NOS SALTA EL ERROR DE QUE UN EQUIPO TIENE QUE TENER 
COMO MINIMO UN ENTRENADOR*/
---SELECCIONAMOS LA TABLA PARA VER LOS ENTRENADORES EN QUE EQUIPOS ESTAN---
SELECT * FROM ENTRENADOR;
/*AL BORRAR EL ENTRENADOR DEL EQUIPO 3, ME SALTA EL ERROR PORQUE SOLO HAY 
 1 ENTRENADOR*/
DELETE FROM ENTRENADOR 
WHERE ID_EQUIPO = 3;
/*AL CAMBIAR DE EQUIPO UN ENTRENADOR, ME SALTA EL ERROR DE QUE NO PUEDO PORQUE 
CADA EQUIPO TIENE QUE TENER COMO MINIMO 1 ENTRENADOR*/
UPDATE ENTRENADOR
SET ID_EQUIPO = 2
WHERE ID_INTEGRANTE = 1;

ROLLBACK;

/*2.TRIGGER LLAMADO:TR_NUM_JUGADORES_MAYOR6*/
/*EN ESTE TRIGGER NOS SALTA ERROR AL METER EL 7TO JUGADOR EN UN MISMO EQUIPO*/

/*VER CUANTOS JUGADORES HAY EN EL EQUIPO 12*/
SELECT * FROM JUGADOR
WHERE ID_EQUIPO=12;

/*INSERTAR 7TO JUGADOR*/
INSERT INTO JUGADOR (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, NACIONALIDAD,
FECHA_NACIMIENTO, NICKNAME, ROL, ID_EQUIPO) VALUES ('Jugador2', 'Apellido2',
'Apellido2', 1400, 'Nacionalidad1', TO_DATE('1990-11-01', 'YYYY-MM-DD'),
'Nick1', 'Rol1',12);

ROLLBACK;

/*3.TRIGGER LLAMADO:TR_INSERTAR_JUGADORES*/
/*EN ESTE TRIGGER NOS SALTA ERROR AL METER EL JUGADOR
EN UNA COMPETICION CERRADA*/

/*VER QUE COMPETICION ESTA CERRADA PARA LUEGO VER EL EQUIPO QUE ESTA EN ELLA*/
SELECT * FROM COMPETICION
WHERE ID_COMPETICION=3;

SELECT * FROM CLASIFICACION
WHERE ID_EQUIPO=9;

/*INSERTAR JUGADOR EN EL EQUIPO 9*/
INSERT INTO JUGADOR (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, NACIONALIDAD,
FECHA_NACIMIENTO, NICKNAME, ROL, ID_EQUIPO)
VALUES ('Alex', 'Gonzalez', 'Martinez', 199000, 'EspaÃ±a',
TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'Alex', 'Delantero', 9);

ROLLBACK;

/*4.TRIGGER LLAMADO:TR_BORRAR_JUGADORES*/
/*EN ESTE TRIGGER NOS SALTA ERROR AL BORRAR EL JUGADOR
EN UNA COMPETICION CERRADA*/
/*VER LOS JUGADORES QUE ESTAN EN UNA COMPETICION CERRADA*/
SELECT * FROM JUGADOR;
SELECT * FROM COMPETICION;
SELECT * FROM CLASIFICACION;
/*AL QUERER BORRAR EL JUGADOR 44 DEL EQUIPO 9, ME SALTA EL ERROR*/
DELETE FROM JUGADOR
WHERE ID_INTEGRANTE=44;

ROLLBACK;

/*5.TRIGGER LLAMADO:TR_INSERTAR_EQUIPOS*/
/*EN ESTE TRIGGER NOS SALTA ERROR AL INSERTAR UN EQUIPO
EN UNA COMPETICION CERRADA*/
/*VER LOS EQUIPOS Y UNA COMPETICION CERRADA*/
SELECT * FROM COMPETICION;
SELECT * FROM CLASIFICACION;
/*AL QUERER INSERTAR EN LA COMPETICION 3, ME SALTA EL ERROR*/
INSERT INTO CLASIFICACION (ID_COMPETICION, ID_EQUIPO, PUNTOS) VALUES (3, 12, 0);

UPDATE EQUIPO
SET NOMBRE='BELLAKOS'
WHERE ID_EQUIPO=8;

ROLLBACK;

/*6.TRIGGER LLAMADO:TR_VALIDAR_SUELDO_MINIMO*/
/*EN ESTE TRIGGER NOS SALTA ERROR AL INSERTAR UN SUELDO MENOR AL SUELDO MINIMO*/
/*VER LAS EQUIPO CON MENOS DE 6 JUGADORES*/
SELECT * FROM JUGADOR
WHERE ID_EQUIPO=12;
/*AL INSERTAR UN JUGADOR CON EL SUELDO MENOR AL SUELDO MINIMO, SALTA EL ERROR*/
INSERT INTO JUGADOR (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, NACIONALIDAD,
FECHA_NACIMIENTO, NICKNAME, ROL, ID_EQUIPO)
VALUES ('Logan', 'Sanchez', 'Lopez', 1000, 'Argentina',
TO_DATE('1993-02-10', 'YYYY-MM-DD'), 'Logan', 'Defensa', 11);

/*7.TRIGGER LLAMADO:TR_MAX_SAL*/
/*EN ESTE TRIGGER NOS SALTA ERROR QUE AL INSERTAR UN SUELDO Y EL TOTAL supera el sueldo 
del equipo que es 200.000*/
--actualizamos el sueldo de un jugador haciendo que la suma de los sueldo 
--del equipo de dicho jugador sume una cntidad mayor que 200.000€
UPDATE JUGADOR
SET SUELDO = 199000
WHERE ID_INTEGRANTE = 1;

--insertamos un jugador cuyo sueldo sumado al sueldo del
-- resto de los jugadores de su equipo sume una cntidad mayor que 200.000€

INSERT INTO JUGADOR (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, ID_EQUIPO)
VALUES ('Alex', 'Gonzalez', 'Martinez', 199000, 'EspaÃ±a', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'Alex', 'Delantero', 1);

/*8.TRIGGER LLAMADO:BORRAR_EQ_CLASI_COMP_CERRADA*/
/*No se puede borrar el equipo porque está asociado a una competición cerrada.*/
SELECT * FROM CLASIFICACION;

DELETE FROM CLASIFICACION 
WHERE ID_EQUIPO = 9;
rollback;
/*9.TRIGGER LLAMADO:TR_DELETE_EQUIPOS*/
/*VER LOS EQUIPO QUE ESTAN EN UNA COMPETICION CERRADA*/
SELECT * FROM EQUIPO;
SELECT * FROM COMPETICION;
SELECT * FROM CLASIFICACION;
/*ELIMINAR EQUIPO Y SALTA ERROR*/
DELETE FROM EQUIPO
WHERE ID_EQUIPO = 9;

/*10.TRIGGER LLAMADO:TR_INSERT_CLASIFICACION*/
/*AL INSERTAR UN EQUIPO DESDE CLASIFICACIONS, SALTA EL ERROR PORQUE LA COMPETICION 
ESTA CERRADA*/
INSERT INTO CLASIFICACION (ID_COMPETICION, ID_EQUIPO, PUNTOS) VALUES (3, 12, 0);


/*11.TRIGGER LLAMADO:menor_a_2*/
/*Cuando trates de cerrar una competicion y el equipo tenga menos de dos 
jugadores, saltar� el error ede que no se puede cerrar*/
SELECT * FROM JUGADOR;
SELECT * FROM EQUIPO;
SELECT * FROM COMPETICION;
SELECT * FROM CLASIFICACION;

DELETE FROM JUGADOR
WHERE ID_INTEGRANTE=4;
 
UPDATE COMPETICION
SET ESTADO = 'cerrado'
WHERE ID_COMPETICION = 1;