
 /*Trigger para que la suma de sueldos de todos los jugadores de un mismo equipo no pueda ser superior a 200.000€*/

CREATE OR REPLACE TRIGGER TR_MAX_SAL
FOR INSERT OR UPDATE ON JUGADOR
COMPOUND TRIGGER
    V_SUELDO_TOTAL_EQUIPO JUGADOR.SUELDO%TYPE;
    E_SUELDOMAXINCORRECTO EXCEPTION;
    NEW_ID_EQUIPO JUGADOR.ID_EQUIPO%TYPE;
    NEW_SUELDO JUGADOR.SUELDO%TYPE;
    OLD_SUELDO JUGADOR.SUELDO%TYPE;
BEFORE EACH ROW IS
BEGIN 
    NEW_ID_EQUIPO := :NEW.ID_EQUIPO;
    NEW_SUELDO := :NEW.SUELDO;
    OLD_SUELDO := :OLD.SUELDO;
END BEFORE EACH ROW;
AFTER STATEMENT IS
BEGIN 
    SELECT SUM(SUELDO) INTO V_SUELDO_TOTAL_EQUIPO
    FROM JUGADOR
    WHERE ID_EQUIPO = NEW_ID_EQUIPO;
    
    IF V_SUELDO_TOTAL_EQUIPO + NVL(NEW_SUELDO, 0) - NVL(OLD_SUELDO, 0) > 200000 THEN
        RAISE E_SUELDOMAXINCORRECTO;
    END IF;
    
EXCEPTION
    WHEN TOO_MANY_ROWS THEN 
        RAISE_APPLICATION_ERROR(-20001,'HAY MAS DE UN VALOR');
    WHEN NO_DATA_FOUND THEN 
        RAISE_APPLICATION_ERROR(-20002,'VALOR NO ENCONTRADO');
    WHEN E_SUELDOMAXINCORRECTO THEN 
        RAISE_APPLICATION_ERROR(-20003,'LA SUMA DE LOS SUELDOS DE UN MISMO EQUIPO NO PUEDE SUPERAR LOS 200.000€');
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20004,'ERROR INESPERADO'); 
END AFTER STATEMENT;
END;

