
-- Inserts para la tabla JUEGO
    INSERT INTO JUEGO (NOMBRE, EMPRESA, FECHA_LANZAMIENTO) VALUES ('Juego1', 'Empresa1', TO_DATE('2022-01-01', 'YYYY-MM-DD'));
    INSERT INTO JUEGO (NOMBRE, EMPRESA, FECHA_LANZAMIENTO) VALUES ('Juego2', 'Empresa2', TO_DATE('2022-02-01', 'YYYY-MM-DD'));
    INSERT INTO JUEGO (NOMBRE, EMPRESA, FECHA_LANZAMIENTO) VALUES ('Juego3', 'Empresa3', TO_DATE('2022-03-01', 'YYYY-MM-DD'));


-- Inserts para la tabla COMPETICION
INSERT INTO COMPETICION (NOMBRE, FECHA_INICIO, FECHA_FIN, ESTADO, ID_JUEGO) VALUES ('Competicion1', TO_DATE('2022-01-01', 'YYYY-MM-DD'), TO_DATE('2022-01-10', 'YYYY-MM-DD'), 'abierto', 1);
INSERT INTO COMPETICION (NOMBRE, FECHA_INICIO, FECHA_FIN, ESTADO, ID_JUEGO) VALUES ('Competicion2', TO_DATE('2022-02-01', 'YYYY-MM-DD'), TO_DATE('2022-02-10', 'YYYY-MM-DD'), 'abierto', 2);
INSERT INTO COMPETICION (NOMBRE, FECHA_INICIO, FECHA_FIN, ESTADO, ID_JUEGO) VALUES ('Competicion3', TO_DATE('2022-03-01', 'YYYY-MM-DD'), TO_DATE('2022-03-10', 'YYYY-MM-DD'), 'abierto', 3);
INSERT INTO COMPETICION (NOMBRE, FECHA_INICIO, FECHA_FIN, ESTADO, ID_JUEGO) VALUES ('Competicion4', TO_DATE('2022-04-01', 'YYYY-MM-DD'), TO_DATE('2022-03-10', 'YYYY-MM-DD'), 'abierto', 4);

-- Inserts para la tabla JORNADA
INSERT INTO JORNADA (ID_JORNADA, ID_COMPETICION, FECHA_ENFRENTAMIENTO) VALUES (1, 1, TO_DATE('2022-01-01', 'YYYY-MM-DD'));
INSERT INTO JORNADA (ID_JORNADA, ID_COMPETICION, FECHA_ENFRENTAMIENTO) VALUES (1,1, TO_DATE('2022-01-01', 'YYYY-MM-DD'));
INSERT INTO JORNADA (ID_JORNADA,ID_COMPETICION, FECHA_ENFRENTAMIENTO) VALUES (2,2, TO_DATE('2022-02-01', 'YYYY-MM-DD'));
INSERT INTO JORNADA (ID_JORNADA,ID_COMPETICION, FECHA_ENFRENTAMIENTO) VALUES (3,3, TO_DATE('2022-03-01', 'YYYY-MM-DD'));

-- Inserts para la tabla PATROCINADOR
INSERT INTO PATROCINADOR (NOMBRE) VALUES ('Patrocinador1');
INSERT INTO PATROCINADOR (NOMBRE) VALUES ('Patrocinador2');
INSERT INTO PATROCINADOR (NOMBRE) VALUES ('Patrocinador3');

-- Inserts para la tabla EQUIPO
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo1', TO_DATE('2000-01-01', 'YYYY-MM-DD'), 1);
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo2', TO_DATE('2000-02-01', 'YYYY-MM-DD'), 1);
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo3', TO_DATE('2000-03-01', 'YYYY-MM-DD'), 1);
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo4', TO_DATE('2000-04-01', 'YYYY-MM-DD'), 1);
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo5', TO_DATE('2000-05-01', 'YYYY-MM-DD'), 2);
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo6', TO_DATE('2000-06-01', 'YYYY-MM-DD'), 2);
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo7', TO_DATE('2000-07-01', 'YYYY-MM-DD'), 2);
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo8', TO_DATE('2000-08-01', 'YYYY-MM-DD'), 2);
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo9', TO_DATE('2000-09-01', 'YYYY-MM-DD'), 3);
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo10', TO_DATE('2000-10-01', 'YYYY-MM-DD'), 3);
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo11', TO_DATE('2000-11-01', 'YYYY-MM-DD'), 3);
INSERT INTO EQUIPO (NOMBRE, FECHA_FUNDACION, ID_PATROCINADOR) VALUES ('Equipo12', TO_DATE('2000-12-01', 'YYYY-MM-DD'), 3);



-- Inserts para la tabla ENFRENTAMIENTO
INSERT INTO ENFRENTAMIENTO (ID_JOR_COMP, ID_ENFRENTAMIENTO, HORA, RESULTADO_LOCAL, RESULTADO_VISITANTE, ID_LOCAL, ID_VISITANTE) VALUES (1, 1, '12:00', 0, 0, 1, 2);
INSERT INTO ENFRENTAMIENTO (ID_JOR_COMP, ID_ENFRENTAMIENTO, HORA, RESULTADO_LOCAL, RESULTADO_VISITANTE, ID_LOCAL, ID_VISITANTE) VALUES (1, 2, '15:00', 0, 0, 3, 1);
INSERT INTO ENFRENTAMIENTO (ID_JOR_COMP, ID_ENFRENTAMIENTO, HORA, RESULTADO_LOCAL, RESULTADO_VISITANTE, ID_LOCAL, ID_VISITANTE) VALUES (2, 3, '12:00', NULL, NULL, 2, 3);

-- Inserts para la tabla USUARIO
INSERT INTO USUARIO (NOMBRE, CONTRASENA, TIPO) VALUES ('ander', 'contrasena1', 'administrador');
INSERT INTO USUARIO (NOMBRE, CONTRASENA, TIPO) VALUES ('oier', 'contrasena2', 'usuario');
INSERT INTO USUARIO (NOMBRE, CONTRASENA, TIPO) VALUES ('inigo', 'contrasena3', 'usuario');

-- Inserts para la tabla JUGADOR
INSERT INTO JUGADOR (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, ID_EQUIPO) VALUES ('Jugador1', 'Apellido1', 'Apellido2', 1000, 'Nacionalidad1', TO_DATE('1990-11-01', 'YYYY-MM-DD'), 'Nick1', 'Rol1', 1);
INSERT INTO JUGADOR (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, ID_EQUIPO) VALUES ('Jugador2', 'Apellido1', 'Apellido2', 1200, 'Nacionalidad2', TO_DATE('1991-02-01', 'YYYY-MM-DD'), 'Nick2', 'Rol2', 1);
INSERT INTO JUGADOR (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, ID_EQUIPO) VALUES ('Jugador3', 'Apellido1', 'Apellido2', 1500, 'Nacionalidad3', TO_DATE('1992-06-01', 'YYYY-MM-DD'), 'Nick3', 'Rol3', 2);

-- Inserts para la tabla ENTRENADOR
INSERT INTO ENTRENADOR (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, ID_EQUIPO) VALUES ('Inigo', 'Apellido1', 'Apellido2', 2000, 1);
INSERT INTO ENTRENADOR (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, ID_EQUIPO) VALUES ('Oier', 'Apellido1', 'Apellido2', 2200, 2);
INSERT INTO ENTRENADOR (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, ID_EQUIPO) VALUES ('Ander', 'Apellido1', 'Apellido2', 2500, 3);


-- Inserts para la tabla ASISTENTE
INSERT INTO ASISTENTE (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, ID_EQUIPO) VALUES ('asistenteBryan', 'Apellido1', 'Apellido2', 1000, 1);
INSERT INTO ASISTENTE (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, ID_EQUIPO) VALUES ('asistenteMikel', 'Apellido1', 'Apellido2', 1200, 2);
INSERT INTO ASISTENTE (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, ID_EQUIPO) VALUES ('asistenteAsier', 'Apellido1', 'Apellido2', 1500, 3);

-- Inserts para la tabla CLASIFICACION
INSERT INTO CLASIFICACION (ID_COMPETICION, ID_EQUIPO, PUNTOS) VALUES (1, 1, 0);
INSERT INTO CLASIFICACION (ID_COMPETICION, ID_EQUIPO, PUNTOS) VALUES (1, 2, 0);
INSERT INTO CLASIFICACION (ID_COMPETICION, ID_EQUIPO, PUNTOS) VALUES (2, 1, 0);
INSERT INTO CLASIFICACION (ID_COMPETICION, ID_EQUIPO, PUNTOS) VALUES (2, 2, 0);
INSERT INTO CLASIFICACION (ID_COMPETICION, ID_EQUIPO, PUNTOS) VALUES (2, 3, 0);
