create or replace TRIGGER TR_NUM_JUGADORES_MAYOR6
BEFORE INSERT OR UPDATE ON JUGADOR
FOR EACH ROW
DECLARE
    V_NUMJUGADORES NUMBER(2);
    V_ESTADO COMPETICION.ESTADO%TYPE;
    E_NUMJUGADORINCORRECTO EXCEPTION;
BEGIN 
    SELECT COUNT(*) INTO V_NUMJUGADORES
    FROM JUGADOR
    WHERE ID_EQUIPO = :NEW.ID_EQUIPO;

    IF V_NUMJUGADORES > 6 THEN 
        RAISE E_NUMJUGADORINCORRECTO;
    END IF; 

EXCEPTION 
    WHEN TOO_MANY_ROWS THEN 
        RAISE_APPLICATION_ERROR(-20001,'HAY MAS DE UN VALOR');
    WHEN NO_DATA_FOUND THEN 
        RAISE_APPLICATION_ERROR(-20002,'VALOR NO ENCONTRADO');
    WHEN E_NUMJUGADORINCORRECTO THEN 
        RAISE_APPLICATION_ERROR(-20003,'EL NUMERO DE JUGADORES ES INCORRECTO');
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20004,'ERROR INESPERADO');
END;


/*-----creacion de trigger bloqueo de equipos cuando la competicion esta iniciada-----*/

CREATE OR REPLACE TRIGGER bloqueo_equipo_cerrada
BEFORE INSERT OR DELETE OR UPDATE ON EQUIPO
FOR EACH ROW
DECLARE
    v_estado_competicion VARCHAR2(20);
BEGIN
    SELECT ESTADO INTO v_estado_competicion FROM COMPETICION WHERE ID_COMPETICION = :NEW.ID_COMPETICION;
    
    IF v_estado_competicion = 'cerrado' THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se pueden realizar operaciones en EQUIPO cuando la competición está cerrada.');
    END IF;
END;

/*----trigger que impide meter mas ususarios cuando la competicion se ha iniciado----*/

CREATE OR REPLACE TRIGGER bloqueo_jugador_cerrada
BEFORE INSERT OR UPDATE OR DELETE ON JUGADOR
FOR EACH ROW
DECLARE
  v_estado VARCHAR2(20);
BEGIN
  SELECT E.estado
  INTO v_estado
  FROM COMPETICION E
  WHERE E.ID_COMPETICION = :NEW.ID_EQUIPO;

  IF v_estado = 'cerrado' THEN
    RAISE_APPLICATION_ERROR(-20001, 'No se pueden realizar cambios en la tabla JUGADOR cuando la competición está cerrada');
  END IF;
END;
/
INSERT INTO JUGADOR (NOMBRE, APELLIDO1, APELLIDO2, SUELDO, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, ID_EQUIPO) VALUES ('Jugador1', 'Apellido1', 'Apellido2', 1000, 'Nacionalidad1', TO_DATE('1990-11-01', 'YYYY-MM-DD'), 'Nick1', 'Rol1', 3);
