/*--------trigger de entrenador ---------*/

--lo que hace es que cuando intentas cambiar el entrenador de equipo 
--teniendo este equipo un entrenador salta (update) y si borras el entrenador y el equipo
--no teine entrenador va a saltar 

CREATE OR REPLACE TRIGGER TR_ENTRENADOR
FOR DELETE OR UPDATE OF ID_EQUIPO ON ENTRENADOR
COMPOUND TRIGGER
    V_CONTADOR_ENTRENADORES NUMBER;
    OLD_ID_EQUIPO ENTRENADOR.ID_EQUIPO%TYPE;
    E_NUMENTRENADORES EXCEPTION;
BEFORE EACH ROW IS
BEGIN 
    OLD_ID_EQUIPO := :OLD.ID_EQUIPO;
END BEFORE EACH ROW;
AFTER STATEMENT IS 
BEGIN
    SELECT COUNT(ID_INTEGRANTE) INTO V_CONTADOR_ENTRENADORES 
    FROM ENTRENADOR
    WHERE ID_EQUIPO = OLD_ID_EQUIPO;
        
    IF V_CONTADOR_ENTRENADORES <1 THEN
        RAISE E_NUMENTRENADORES;
    END IF;
EXCEPTION
    WHEN E_NUMENTRENADORES THEN 
        RAISE_APPLICATION_ERROR(-20003, 'ERROR: DEBE HABER AL MENOS 1 ENTRENADOR');
    WHEN TOO_MANY_ROWS THEN 
        RAISE_APPLICATION_ERROR(-20001, 'HAY MÁS DE UN VALOR');
    WHEN NO_DATA_FOUND THEN 
        RAISE_APPLICATION_ERROR(-20002, 'VALOR NO ENCONTRADO');
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20004, 'ERROR INESPERADO');
END AFTER STATEMENT;
END TR_ENTRENADOR;