
 /*Trigger para que la suma de sueldos de todos los jugadores de un mismo equipo no pueda ser superior a 200.000€*/

 CREATE OR REPLACE TRIGGER TR_MAX_SAL
BEFORE INSERT OR UPDATE ON JUGADOR
FOR EACH ROW
DECLARE 
    V_SUELDO_TOTAL_EQUIPO JUGADOR.SUELDO%TYPE;
    E_SUELDOMAXINCORRECTO EXCEPTION;
BEGIN 
    SELECT SUM(SUELDO) INTO V_SUELDO_TOTAL_EQUIPO
    FROM JUGADOR
    WHERE ID_EQUIPO = :NEW.ID_EQUIPO;
    
    IF V_SUELDO_TOTAL_EQUIPO + NVL(:NEW.SUELDO, 0) - NVL(:OLD.SUELDO, 0) > 200000 THEN
        RAISE E_SUELDOMAXINCORRECTO;
    END IF;
    
EXCEPTION
    WHEN TOO_MANY_ROWS THEN 
        RAISE_APPLICATION_ERROR(-20001,'HAY MAS DE UN VALOR');
    WHEN NO_DATA_FOUND THEN 
        RAISE_APPLICATION_ERROR(-20002,'VALOR NO ENCONTRADO');
    WHEN E_SUELDOMAXINCORRECTO THEN 
        RAISE_APPLICATION_ERROR(-20003,'LA SUMA DE LOS SUELDOS DE UN MISMO EQUIPO NO PUEDE SUPERAR LOS 200.000€');
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20004,'ERROR INESPERADO'); 
END;

